@startuml
'https://plantuml.com/object-diagram

object London
object Washington
object Berlin
object Task
object Epic
object SubTasks
object Status
object Hfjdd3
object Hfjdde
object Hfjdddss
object Hfjddd
object Hfjdd2d

map CapitalCity {
 UK *-> Task
 USA *--> Washington
 Germany *---> Berlin
 Epic *----> Task
}
map Task {
id
title
description
status
}


NewYork --> CapitalCity::USA
@enduml
